name: Run Did You Know Uploader Pipeline

on:
  workflow_dispatch:  # manual trigger
  push:
    branches: [ main ]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
      YOUTUBE_ACCESS_TOKEN: ${{ secrets.YOUTUBE_ACCESS_TOKEN }}
      DID_API_KEY: ${{ secrets.DID_API_KEY }}

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 🧙 Install ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick
    - name: ▶️ Step 1 Generate Scripts
      run: |
        cd DidYouKnowUploader
        python generateScripts.py

    - name: ▶️ Step 2 Generate D-ID Videos
      run: |
        cd DidYouKnowUploader
        python generateVideos.py

    - name: ▶️ Step 3 Add Captions
      run: |
        cd DidYouKnowUploader
        python editVideos.py

    - name: ▶️ Step 4 Upload to YouTube
      run: |
        cd DidYouKnowUploader
        python bulk_upload.py
