name: Run Did You Know Uploader Pipeline

on:
  workflow_dispatch:  # manual trigger
  #push:
    #branches: [ main ]
  #schedule:
    #- cron: '0 6 */2 * *'  # Every 2 days at 06:00 UTC
jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
      YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
      YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
      YOUTUBE_ACCESS_TOKEN: ${{ secrets.YOUTUBE_ACCESS_TOKEN }}
      DID_API_KEY: ${{ secrets.DID_API_KEY }}

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🐍 Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 📦 Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 🧙 Install ImageMagick
      run: sudo apt-get update && sudo apt-get install -y imagemagick

    - name: 🛡️ Override ImageMagick Security Policy for MoviePy
      run: |
        sudo tee /etc/ImageMagick-6/policy.xml > /dev/null <<EOF
        <policymap>
          <policy domain="coder" rights="read|write" pattern="PDF" />
          <policy domain="coder" rights="read|write" pattern="LABEL" />
          <policy domain="coder" rights="read|write" pattern="TEXT" />
          <policy domain="path" rights="read|write" pattern="@*" />
        </policymap>
        EOF

    - name: ▶️ Step 1 Generate Scripts
      run: |
        cd DidYouKnowUploader
        python generateScripts.py

    - name: ▶️ Step 2 Generate D-ID Videos
      run: |
        cd DidYouKnowUploader
        python generateVideos.py

    - name: ▶️ Step 3 Add Captions
      run: |
        cd DidYouKnowUploader
        python editVideos.py

    - name: ▶️ Step 4 Upload to YouTube
      run: |
        cd DidYouKnowUploader
        python bulk_upload.py
