name: 📤 InstaReel YouTube Upload

on:
  workflow_dispatch:
    inputs:
      URL:
        description: "Instagram Audio Page URL (e.g. https://instagram.com/music/xyz...)"
        required: true
        type: string

jobs:
  process_and_upload:
    runs-on: ubuntu-latest

    env:
      YT_FG_CLIENT_ID: ${{ secrets.YT_FG_CLIENT_ID }}
      YT_FG_CLIENT_SECRET: ${{ secrets.YT_FG_CLIENT_SECRET }}
      YT_FG_REFRESH_TOKEN: ${{ secrets.YT_FG_REFRESH_TOKEN }}
      INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
      INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
      INSTAGRAM_REEL_URL: ${{ github.event.inputs.URL }}

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v4

      - name: 🐍 Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 📦 Install Python + Playwright Dependencies
        run: |
          pip install -r requirements.txt || true
          pip install playwright python-dotenv yt-dlp \
              google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2
          playwright install chromium

      - name: 🔍 Step 1 - Extract Reel URLs from Audio Page
        run: |
          cd ReelUploader
          python ReelURLFetcher.py --url "$INSTAGRAM_REEL_URL"

      - name: 📥 Step 2 - Download Reels from URL List
        run: |
          cd ReelUploader
          python reelDownloader.py

      - name: 📤 Step 3 - Upload Reels to YouTube Shorts
        run: |
          cd ReelUploader
          python uploadYoutube.py
